server:
  port: 8888		# Config Service application이 듣는 포트
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wook-J/config-repo.git	# 설정데이터 저장 벡엔드로 사용할 원격 깃 저장소의 URL
          default-label: main	# 이 설정에 따라 기본적으로 main 브랜치에서 설정데이터 반환
          timeout: 5			# 원격 저장소와의 연결 시 시간한도
          clone-on-start: true	# 서비스 시작 시 리모트 저장소의 복제본을 로컬에 저장
          force-pull: true		# 로컬 저장본이 원격 저장소와 다를 경우 무조건 원격 저장소로부터 다운로드